/* pgmigrate-encoding: utf-8 */

-- config.tag

INSERT INTO config.tag (id, tag_type, name) VALUES (1, 'cms', '1С-Битрикс');
INSERT INTO config.tag (id, tag_type, name) VALUES (2, 'calltracking', 'Alloka');
INSERT INTO config.tag (id, tag_type, name) VALUES (3, 'cms', 'AMIRO.CMS');
INSERT INTO config.tag (id, tag_type, name) VALUES (4, 'leadgen', 'callbackhunter.com');
INSERT INTO config.tag (id, tag_type, name) VALUES (5, 'calltracking', 'Calltouch');
INSERT INTO config.tag (id, tag_type, name) VALUES (6, 'calltracking', 'Calltracking.ru');
INSERT INTO config.tag (id, tag_type, name) VALUES (7, 'consultant', 'Cloudim');
INSERT INTO config.tag (id, tag_type, name) VALUES (8, 'cms', 'CMS Made Simple');
INSERT INTO config.tag (id, tag_type, name) VALUES (9, 'consultant', 'Comagic');
INSERT INTO config.tag (id, tag_type, name) VALUES (10, 'cms', 'DiAfan');
INSERT INTO config.tag (id, tag_type, name) VALUES (11, 'cms', 'DJEM');
INSERT INTO config.tag (id, tag_type, name) VALUES (12, 'cms', 'DLE');
INSERT INTO config.tag (id, tag_type, name) VALUES (13, 'cms', 'Drupal');
INSERT INTO config.tag (id, tag_type, name) VALUES (14, 'cms', 'e107');
INSERT INTO config.tag (id, tag_type, name) VALUES (15, 'webstat', 'Google Analytics');
INSERT INTO config.tag (id, tag_type, name) VALUES (16, 'tag_manager', 'Google Tag Manager');
INSERT INTO config.tag (id, tag_type, name) VALUES (17, 'consultant', 'GoTalk');
INSERT INTO config.tag (id, tag_type, name) VALUES (18, 'leadgen', 'hookmyvisit.com');
INSERT INTO config.tag (id, tag_type, name) VALUES (19, 'cms', 'HostCMS');
INSERT INTO config.tag (id, tag_type, name) VALUES (20, 'cms', 'InstantCMS');
INSERT INTO config.tag (id, tag_type, name) VALUES (21, 'consultant', 'JivoSite');
INSERT INTO config.tag (id, tag_type, name) VALUES (22, 'cms', 'Joomla!');
INSERT INTO config.tag (id, tag_type, name) VALUES (23, 'consultant', 'Krible');
INSERT INTO config.tag (id, tag_type, name) VALUES (24, 'webstat', 'LiveInternet');
INSERT INTO config.tag (id, tag_type, name) VALUES (25, 'consultant', 'Liveperson');
INSERT INTO config.tag (id, tag_type, name) VALUES (26, 'consultant', 'Livetex');
INSERT INTO config.tag (id, tag_type, name) VALUES (27, 'consultant', 'Livezilla');
INSERT INTO config.tag (id, tag_type, name) VALUES (28, 'consultant', 'Marva');
INSERT INTO config.tag (id, tag_type, name) VALUES (29, 'consultant', 'Mibew');
INSERT INTO config.tag (id, tag_type, name) VALUES (30, 'cms', 'MODx');
INSERT INTO config.tag (id, tag_type, name) VALUES (31, 'cms', 'NetCat');
INSERT INTO config.tag (id, tag_type, name) VALUES (32, 'consultant', 'netroxsc');
INSERT INTO config.tag (id, tag_type, name) VALUES (33, 'consultant', 'Olark');
INSERT INTO config.tag (id, tag_type, name) VALUES (34, 'cms', 'PHPShop');
INSERT INTO config.tag (id, tag_type, name) VALUES (35, 'consultant', 'RedHelper');
INSERT INTO config.tag (id, tag_type, name) VALUES (36, 'cms', 'S.Builder');
INSERT INTO config.tag (id, tag_type, name) VALUES (37, 'consultant', 'SiteHelp');
INSERT INTO config.tag (id, tag_type, name) VALUES (38, 'consultant', 'SPEXE');
INSERT INTO config.tag (id, tag_type, name) VALUES (39, 'cms', 'TYPO3');
INSERT INTO config.tag (id, tag_type, name) VALUES (40, 'cms', 'UMI');
INSERT INTO config.tag (id, tag_type, name) VALUES (41, 'consultant', 'WebConsult');
INSERT INTO config.tag (id, tag_type, name) VALUES (42, 'consultant', 'WebIM');
INSERT INTO config.tag (id, tag_type, name) VALUES (43, 'cms', 'WordPress');
INSERT INTO config.tag (id, tag_type, name) VALUES (44, 'consultant', 'Zopim');
INSERT INTO config.tag (id, tag_type, name) VALUES (45, 'calltracking', 'Целевой Звонок by Яндекс.Метрика');
INSERT INTO config.tag (id, tag_type, name) VALUES (46, 'webstat', 'Яндекс.Метрика');
INSERT INTO config.tag (id, tag_type, name) VALUES (47, 'cms', 'OpenCart');
INSERT INTO config.tag (id, tag_type, name) VALUES (48, 'hack', 'MySQL Error');
INSERT INTO config.tag (id, tag_type, name) VALUES (49, 'hack', 'POST form');
INSERT INTO config.tag (id, tag_type, name) VALUES (50, 'forum', 'Invision Power Board');
INSERT INTO config.tag (id, tag_type, name) VALUES (51, 'forum', 'phpBB');
INSERT INTO config.tag (id, tag_type, name) VALUES (52, 'cms', 'uCoz');
INSERT INTO config.tag (id, tag_type, name) VALUES (53, 'javascript', 'jquery');
INSERT INTO config.tag (id, tag_type, name) VALUES (54, 'hack', 'Local URL with arguments');
INSERT INTO config.tag (id, tag_type, name) VALUES (55, 'calltracking', 'CoMagic');
INSERT INTO config.tag (id, tag_type, name) VALUES (56, 'consultant', 'Onicon');
INSERT INTO config.tag (id, tag_type, name) VALUES (57, 'consultant', 'SiteHeart');
INSERT INTO config.tag (id, tag_type, name) VALUES (58, 'callback', 'RoboCall');
INSERT INTO config.tag (id, tag_type, name) VALUES (59, 'consultant', 'SteamWood');
INSERT INTO config.tag (id, tag_type, name) VALUES (60, 'social', 'Twitter "Share a link" button');
INSERT INTO config.tag (id, tag_type, name) VALUES (61, 'social', 'Twitter "Follow" button');
INSERT INTO config.tag (id, tag_type, name) VALUES (62, 'webstat', 'OpenStat');
INSERT INTO config.tag (id, tag_type, name) VALUES (63, 'cms', 'Setup.ru');
INSERT INTO config.tag (id, tag_type, name) VALUES (66, 'hack', 'MOZGIII');
INSERT INTO config.tag (id, tag_type, name) VALUES (67, 'hack', 'pensnarik');
INSERT INTO config.tag (id, tag_type, name) VALUES (68, 'cms', 'Magento');

SELECT pg_catalog.setval('config.tag_id_seq', 68, false);
