/* pgmigrate-encoding: utf-8 */

-- config.expression

INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (1, 17, true, false, '<a.{1,500}?onclick=".{0,1000}?(DtalkOpenChat).{0,1000}?".{0,1000}?>.{0,1000}?(<\/a>)?', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (2, 39, true, false, '<script.{0,50}?([''|"|\/]fileadmin\/).{0,50}?><\/script>|<meta name="generator" content=".{0,50}?(TYPO3).{0,50}?"', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (3, 15, true, true, '<script.{0,1000}?>.{0,1000}?(google-analytics).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (4, 35, true, false, '<script.{0,500}?>.{0,1000}?(web\.redhelper\.ru).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (5, 38, true, false, '<script.{1,100}?(spexe\.(ru|net|com)).{1,100}?<\/script>|<!--\s{0,100}begin\s{0,100}spexe\s{0,100}code\s{0,100}-->(.{0,100}?)<!--\s{0,100}end\s{0,100}spexe\s{0,100}code\s{0,100}-->', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (6, 10, true, false, '<meta content.{1,1000}diafan', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (7, 28, true, true, '<script.{0,1000}?>.{0,1000}?(account\.marva\.ru).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (8, 25, true, false, '<script.{0,500}?>.{0,1000}?(liveperson.com).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (9, 13, true, true, '<script.{0,1000}?([''|"|\/]drupal).{1,1000}?><\/script>|<script.{0,1000}?>.{0,1000}?(drupal).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (10, 26, true, true, '<script.{0,700}?>.{0,700}?(livetex\.ru).{0,700}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (11, 8, true, false, '<meta.{1,50}?generator.{1,50}?cms made simple.{1,50}\/>', true);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (12, 30, true, false, '<script.{0,50}?([''|"|\/]assets\/templates).{0,50}?><\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (13, 34, true, false, '<meta.{1,50}?content.{1,50}?PHPShop.{1,50}?\/>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (14, 2, true, true, '<script.{0,200}?>.{0,1000}?(_alloka).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (15, 36, true, false, '<script.{0,50}?([''|"|\/]scripts\/fsmenu\.js).{0,50}?><\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (16, 3, true, true, '<meta name=("|'')GENERATOR("|'') content=("|'').{0,100}?(amiro).{0,200}?("|'')>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (17, 24, true, true, '<script.{0,100}?>.{0,1000}?counter\.yadro\.ru.{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (18, 7, true, false, '<script.{0,100}?>.{0,1000}?static\.cloudim\.ru.{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (19, 14, true, true, '<script.{0,1000}?(e107_files\/).{0,1000}?><\/script>|<link.{0,1000}?(e107_files\/).{0,1000}?>|<script.{0,1000}?(e107_themes\/).{0,1000}?><\/script>|<link.{0,1000}?(e107_themes\/).{0,1000}?>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (20, 21, true, true, '<script.{0,200}?>.{1,1000}?(jivosite).{1,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (21, 27, true, false, '<!\-\-\s*http:\/\/www\.LiveZilla\.net Chat.{1,100}Code \-\-\>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (22, 44, true, true, '<script.{0,1000}?>.{1,1000}?zopim\.com.{1,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (23, 46, true, true, '<script.{0,100}?>.{1,1000}?(Ya.Metrika).{1,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (24, 11, true, false, '<script.{0,50}?([''|"|\/][^plugins\/]system\/js\/).{0,50}?><\/script>|<link.{0,50}?([''|"|\/][^plugins\/]system\/css\/).{0,50}?>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (25, 29, true, true, '<a.{1,100}?onclick=".{1,200}?''mibew''.{1,200}?".{1,500}?>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (26, 41, true, false, '<script.{1,500}?src=".{0,1000}?(consultsystems\.ru\/script).{0,1000}?".{0,1000}?>.{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (27, 5, true, true, '<script.{0,100}?>.{1,1000}?mod\.calltouch\.ru.{1,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (28, 22, true, false, '<link.{0,50}?[^bitrix](\/templates\/.{0,50}?\/template\.css).{0,50}?>|<meta name="Generator" content=".{0,50}?(joomla).{0,50}?"|<link.{0,50}?(\/components\/com_).{0,50}?>|<script.{0,50}?(\/components\/com_).{0,50}?><\/script>|<script.{0,50}?(\/plugins\/system\/).{0,50}?><\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (29, 43, true, true, '<script.{0,100}?([''|"|\/]wp-content\/).{0,100}?><\/script>|<link.{1,500}?(wp-content\/).{1,500}?>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (30, 23, true, true, '<script.{0,500}?>.{1,1000}?chat\.krible\.ru.{1,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (31, 33, true, false, 'loader: "static\.olark\.com\/jsclient', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (32, 45, true, false, '<script.{0,100}src=(''|")\/\/?mc\.yandex\.ru\/metrika\/phone\.js\?counter=\d+(''|").{0,100}?>.{0,200}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (33, 31, true, false, '<script.{0,50}?([''|"|\/]netcat).{0,50}?><\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (34, 1, true, false, '<script.{0,50}?([''|"|\/]bitrix).{0,50}?><\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (35, 12, true, false, '<script.{0,500}?([''|"|\/]engine\/).{0,500}?><\/script>|<link.{0,500}?([''|"|\/]engine\/).{0,500}?>|<script.{0,500}?>.{0,1000}?(dle_root).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (36, 42, true, true, '<script.{0,1000}?src=".{0,200}?webim\.ru.{1,1000}?".{1,1000}?>|\.src.{1,300}?=.{1,300}?".{1,200}?webim\.ru.{1,200}?"', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (37, 40, true, false, 'umi\:element\-id', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (38, 32, true, false, '<script.{1,500}?src=".{0,500}?(code\.netroxsc\.ru).{0,500}?"><\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (39, 6, true, true, '<script.{0,200}?>.{1,1000}?calltracking\.ru.{1,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (40, 19, true, false, '<script.{0,50}?([''|"|\/]hostcmsfiles).{0,50}?><\/script>|<link.{0,50}?([''|"|\/]hostcmsfiles).{0,50}?>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (41, 20, true, false, '<meta name="generator".{0,100}?InstantCMS.{0,100}?>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (42, 37, true, false, '<script.{0,500}?>.{0,1000}?(sitehelp\.inkiev\.net).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (44, 47, true, false, 'OpenCart is open source software and you are free to remove the powered by OpenCart if you want', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (45, 9, true, false, '<script.{1,500}?(app\.comagic\.ru\/static\/comagic\/comagic\.min\.js).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (46, 16, true, true, '<script.{0,100}?>.{1,1000}?googletagmanager\.com.{1,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (47, 18, true, false, '<script src="http://hookmyvisit.com/js/escape-tracker.min.js" charset="UTF-8"></script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (48, 4, true, false, '<script type="text/javascript" src="http://callbackhunter.com/widget/tracker.js" charset="UTF-8"></script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (49, 5, true, false, 'var a = ''all'', b = ''tou''; var src = b \+ ''c'' \+''h''; src = ''m'' \+ ''o'' \+ ''d\.c'' \+ a \+ src;', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (50, 5, true, true, '<script.{0,1000}?>.{0,1000}?(var calltouch_area_id).{0,1000}?<\/script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (52, 48, true, false, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (53, 49, true, true, '<form.{1,100} method\s{0,10}=\s{0,10}[''"]?post[''"]?.{0,500}>', true);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (54, 50, true, true, '<div\s+.{0,100}align\s{0,10}=\s{0,10}[''"]?center[''"]?.{0,100}>.{0,100}Powered By.{0,100}invision.{0,100}board', true);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (55, 50, true, true, '<p\s+id\s{0,10}=\s{0,10}[''"]copyright[''"]>.{0,100}<a href=[''"]http://www\.invisionpower\.com', true);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (56, 51, true, true, 'Создано на основе <a href\s{0,10}=\s{0,10}[''"]?http://www\.phpbb\.com', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (57, 52, true, false, '<link type="text/css" rel="StyleSheet" href="http://[^"]{1,100}ucoz\.net[^"]{1,100}\.css"', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (58, 53, true, false, '<script.{0,100}?src\s{0,10}=\s{0,10}[''"][^''"]{1,200}jquery[a-z0-9-.]{0,50}\.js[''"]', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (59, 54, true, false, 'http://(www\.)?%(domain)s\/[A-Za-z0-9\.=]+\?[A-Za-z0-9]+=[A-Za-z0-9]+', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (60, 55, true, false, '<script type="text/javascript" async src="//app.comagic.ru/static/cs.min.js">.{0,10}</script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (61, 56, true, false, '<script type=[''"]text/javascript[''"].{1,500}id=[''"]onicon_loader[''"]\s{1,10}src=[''"]http://cp\.onicon\.ru', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (62, 57, true, false, 'var url\s{0,3}=\s{0,3}[''"]widget\.siteheart\.com/widget/sh/[''"]', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (63, 58, true, false, '<script.{1,200}src=[''"]http://rbcall\.com/witget/index\.php{1,200}[''"]', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (64, 59, true, false, '<script type=[''"]text/javascript[''"] src=[''"]https://clients\.streamwood\.ru/StreamWood/sw\.js[''"]', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (65, 60, true, false, '<a href=[''"]https://twitter\.com/share[''"] class=[''"]twitter-share-button[''"] data-via=("[^"]+"|''[^'']+'')>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (66, 61, true, false, '<a href=[''"]https://twitter\.com/([^''"]+)[''"] class=[''"]twitter-follow-button[''"].{1,300}?>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (67, 62, true, false, '<span id=[''"]openstat(\d+)[''"]>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (68, 63, true, false, '<link rel=[''"]stylesheet[''"].{1,300}?href=[''"]/_s/css/new/includer\.css[''"]', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (69, 58, true, false, '<script src=[''"]http://rbcall\.com/script\.php.{1,200}?></script>', false);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (70, 66, true, false, '\bmozgiii\b', true);
INSERT INTO config.expression (id, tag_id, is_active, is_multiline, code, is_ignorecase) VALUES (71, 67, true, false, '\bpensnarik\b', false);

SELECT pg_catalog.setval('config.expression_id_seq', 71, false);
