language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install pytest
bedore_script:
  - python3 setup.py sdist
  - find dist -name "*.tar.gz" -exec sudo -E pip3 install -U {} \;
# command to run tests
script:
  - pytest -q tests/test_web.py
