version: '3'

networks:
  datatrace:

services:
  datatrace-db:
    image: datatrace-db
    build: ./db
    environment:
      PG_LOG_MIN_MESSAGES: 'info'
      PG_LOG_MIN_DURATION_STATEMENT: '0'
    networks:
      - datatrace
    ports:
      - '25000:5432'
  datatrace-app:
    image: datatrace-app
    build: ./app
    networks:
      - datatrace
    deploy:
      mode: replicated
      replicas: 4
    environment:
      DATATRACE_DB: 'postgresql://datatrace@datatrace-db/datatrace'
  datatrace-dispatcher:
    image: datatrace-app
    build: ./app
    networks:
      - datatrace
    environment:
      DATATRACE_DB: 'postgresql://dispatcher@datatrace-db/datatrace'
    entrypoint: /usr/local/bin/datatrace-dispatcher
  datatrace-web:
    image: datatrace-web
    networks:
      - datatrace
    ports:
      - '80:80'
    depends_on:
        - "datatrace-db"